### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by janlorenz** [RoccoPaolillo/css2019#1]
I'd like to remove any data in the root directory (the stuff not in TownData)? Do we need anything there still?
I'd also like to  reduce the nlogo files we are working on in that directory. 
Maybe create a NetLogo-Backup directory for really needed old version. Rocco what do you need?

**Comment by RoccoPaolillo** [comment]
Yes go ahead and simplify as much. We need data in shp_NetLogo.
I have a copy on my desktop with current version.
No necessary file to me. Nlogo can be rewritten.

**Comment by janlorenz** [comment]
OK, deleted the data. Is "step models" a kind of nlogo backup? Should I put Schelling_GIS (first version) there? 
Do we need the shapefiles.Rmd still? New R code producing the GIS data is in "R" now.

**Comment by RoccoPaolillo** [comment]
Yes you can delete: was the beackup in Sardinia with initial tests.
 "SchellingGIS_2.nlogo" (and "SchellingGIS_Bremen"), last nlogo to stay and build on I assume. Older version will stay in history and my ideas can be reproduced there.
Can be deleted also: shapefiles.Rmd (theory) and UtilityFunctions.Rmd (formulae)

**Comment by janlorenz** [comment]
OK. I'll keep the Utility functions because that is still an interesting thing to analyse and decide.
